apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-ollama-resources.yaml
    target:
      kind: Deployment
      name: ollama
  - path: patch-open-webui-resources.yaml
    target:
      kind: Deployment
      name: open-webui