apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: llm-devops
spec:
  template:
    spec:
      containers:
        - name: open-webui
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi